name: my first workflow
#on: [push, fork]
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: welcome message for joiner
      run: echo "first github hello action excuted"

    - name: multiline steps execute
      run: |
        echo "multiline commands"
        pwd
        cat README.md

    - name: one time
      run: ls -la

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Random job step
      run: echo "This is a random job step"

    - name: Second job step
      run: echo "Second job executed after first job success"

