name: Main Workflow

on:
  push:
    branches-ignore:
      - feature-1
      - feature-2
      - release04112025
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/reusable.yml
        with:
          environment: ${{ github.event.inputs.environment || 'dev' }}
        id: set_output
    outputs:
      result: ${{ steps.set_output.outputs.result }}

  consume-output:
    needs: call-reusable
    runs-on: ubuntu-latest
    steps:
      - name: Output from reusable
        run: echo "Reusable output was ${{ needs.call-reusable.outputs.result }}"
