name: Main Workflow

on:
  push:
    branches-ignore:
      - feature-1
      - feature-2
      - release04112025
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}

  consume-output:
    needs: call-reusable
    runs-on: ubuntu-latest
    steps:
      - name: Output all results from reusable
        run: |
          echo "Result output: ${{ needs.call-reusable.outputs.result }}"
          echo "Profile value: ${{ needs.call-reusable.outputs.profile_value }}"
          echo "All outputs context: ${{ toJSON(needs.call-reusable.outputs) }}"