name: Create Issue

on:
    workflow_dispatch:

permissions:
    issues: write

jobs:
    create-issue:
        runs-on: ubuntu-latest
        steps:
            - name: Create an issue
              uses: actions/github-script@v6
              with:
                    script: |
                        const { context, github } = require('@actions/github');
                        const issueTitle = "Automated Issue Title";
                        const issueBody = "This issue was created automatically by a GitHub Actions workflow.";
                        
                        await github.rest.issues.create({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            title: issueTitle,
                            body: issueBody,
                        });
            - name: echo the success message
              if: success() && github.event_name == 'workflow_dispatch'
              run: echo "Issue created successfully!"