name: Create Issue

on:
    workflow_dispatch:

permissions:
    issues: write

jobs:
    create-issue:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Create an issue
              run: |
                gh issue create --title "Automated Issue Title" --body "This issue was created automatically by a GitHub Actions workflow."
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: echo the success message
              if: success() && github.event_name == 'workflow_dispatch'
              run: echo "Issue created successfully!"